// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggnsfttbhciizqpektor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbnNmdHRiaGNpaXpxcGVrdG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDYyOTgsImV4cCI6MjA2MzI4MjI5OH0.d2KLYpOyyIbmo2jD-VwwXTa5yPvSvFyurbSzHW1zcsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);